const blogData = [
        {
          id:1,
          title: "something new about pastry will be developed in 2022",
          date: "October 19,2021",
          link: "/shop",
          img: "https://media1.popsugar-assets.com/files/thumbor/vWZdDqUVPa0LsDRVh77mId3IlLk/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2016/10/26/757/n/40952353/d1de347a50c72ab7_18._StockSnap_TU3KHCS4ZC_1_/i/cake.jpg ",
          des: "Things you should know about cakes Donec sed erat ut magna suscipit mattis. Aliquam erat volutpat. Morbi in orci risus.…",
          btnlink: "",
        },
        {
          id:2,
          title: "something new about pastry will be developed in 2022",
          date: "October 19,2021",
          link: "/shop",
          img: "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
          des: "Things you should know about cakes Donec sed erat ut magna suscipit mattis. Aliquam erat volutpat. Morbi in orci risus.…",
          btnlink: "",
        },
        {
          id:3,
          title: "something new about pastry will be developed in 2022",
          date: "October 19,2021",
          link: "/shop",
          img: "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
          des: "Things you should know about cakes Donec sed erat ut magna suscipit mattis. Aliquam erat volutpat. Morbi in orci risus.…",
          btnlink: "",
        },
        {
          id:4,
          title: "something new about pastry will be developed in 2022",
          date: "October 19,2021",
          link: "/shop",
          img: "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
          des: "Things you should know about cakes Donec sed erat ut magna suscipit mattis. Aliquam erat volutpat. Morbi in orci risus.…",
          btnlink: "",
        },
        {
          id:5,
          title: "something new about pastry will be developed in 2022",
          date: "October 19,2021",
          link: "/shop",
          img: "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
          des: "Things you should know about cakes Donec sed erat ut magna suscipit mattis. Aliquam erat volutpat. Morbi in orci risus.…",
          btnlink: "",
        },
        {
          id:6,
          title: "something new about pastry will be developed in 2022",
          date: "October 19,2021",
          link: "/shop",
          img: "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
          des: "Things you should know about cakes Donec sed erat ut magna suscipit mattis. Aliquam erat volutpat. Morbi in orci risus.…",
          btnlink: "",
        },
        {
          id:7,
          title: "something new about pastry will be developed in 2022",
          date: "October 19,2021",
          link: "/shop",
          img: "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
          des: "Things you should know about cakes Donec sed erat ut magna suscipit mattis. Aliquam erat volutpat. Morbi in orci risus.…",
          btnlink: "",
        },
        {
          id:8,
          title: "something new about pastry will be developed in 2022",
          date: "October 19,2021",
          link: "/shop",
          img: "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
          des: "Things you should know about cakes Donec sed erat ut magna suscipit mattis. Aliquam erat volutpat. Morbi in orci risus.…",
          btnlink: "",
        },
        {
          id:9,
          title: "something new about pastry will be developed in 2022",
          date: "Augest 19,2021",
          link: "/shop",
          img: "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
          des: "Things you should know about cakes Donec sed erat ut magna suscipit mattis. Aliquam erat volutpat. Morbi in orci risus.…",
          btnlink: "",
        },
        {
          id:10,
          title: "something new about pastry will be developed in 2022",
          date: "October 1,2022",
          link: "/shop",
          img: "https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
          des: "Things you should know about cakes Donec sed erat ut magna suscipit mattis. Aliquam erat volutpat. Morbi in orci risus.…",
          btnlink: "",
        },
  ];
  export default blogData